{"version":3,"sources":["Pormise.reject.es6"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;AAAA;;;AAGA,MAAI,IAAI,kBAAQ,MAAR,CAAe,KAAf,CAAR;AACA;AACA,MAAI,IAAI,sBAAY,UAAC,OAAD,EAAU,MAAV;AAAA,WAAqB,OAAO,KAAP,CAArB;AAAA,GAAZ,CAAR;;AAEA,IAAE,IAAF,CAAO,IAAP,EAAa,UAAU,CAAV,EAAY;AACrB,YAAQ,GAAR,CAAY,CAAZ;AACH,GAFD;AAGA;AACA;AACA","file":"Pormise.reject.js","sourcesContent":["/**\r\n * 返回一个新的Promise实例，该实例的状态为rejected。它的参数用法与Promise.resolve方法完全一致。\r\n */\r\nvar p = Promise.reject('出错了');\r\n// 等同于\r\nvar p = new Promise((resolve, reject) => reject('出错了'));\r\n\r\np.then(null, function (s){\r\n    console.log(s)\r\n});\r\n// 出错了\r\n// 上面代码生成一个Promise对象的实例p，状态为rejected，回调函数会立即\r\n// 执行。"]}